name = "Ryniworld The Sequel!"
author = "Erisatis Alterna, rynizx"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41b8ba2ac6d41c88ba172e90fbd15945f28e189045c2ad5b3abf921837705b5a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"
unsup = "1.2.7"
