name = "Ryniworld The Sequel!"
author = "Erisatis Alterna, rynizx"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cf0267f5ef0363596c20b5abdc8d68db96ab4fb687b3104086ce9108271bb8e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"
unsup = "1.2.7"
