name = "Ryniworld The Sequel!"
author = "Erisatis Alterna, rynizx"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "849bfac2be0ae5698f64f27014fd6ca51970e85fe67b3c6bd8aa921cc5bcab31"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"
unsup = "1.2.7"
