name = "Ryniworld The Sequel!"
author = "Erisatis Alterna, rynizx"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c33af52609cac0a76ffa66947c474f9b4ad4084112147eceafde4d2e176168b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"
unsup = "1.2.7"
