name = "Ryniworld The Sequel!"
author = "Erisatis Alterna, rynizx"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4c344675dd40d8387f2c8d38edc01343a385f5719b8b7dec0d078486081431a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"
unsup = "1.2.7"
